name: GitHub Actions Build Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build-and-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./chess-app
    strategy: 
      matrix:
        node_version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn config set network-timeout 600000 -g
      - run: yarn install
      - run: yarn run build
      - run: yarn test